version: "3"
services:
  homeassistant:
    build:
      context: .
      dockerfile: Dockerfile
    #must be on host network inoder for discovery to work, if you know what ports your devises need for communication uncomment ports below and add them. If you add explicit ports for your services feel free to submit a pull request to have known ports be added to the readme
    #ports:
    #  - "8123:8123"
    network_mode: "host"
    volumes:
      - ./conf:/root/.homeassistant
